config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :depts
  resources :batches

end

app/models/batch.rb
class Batch < ActiveRecord::Base
end

app/models/dept.rb
class Dept < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_batch, only: [:show, :edit, :update, :destroy]

  # GET /batches
  # GET /batches.json
  def index
    @batches = Batch.all
  end

  # GET /batches/1
  # GET /batches/1.json
  def show
  end

  # GET /batches/new
  def new
    @batch = Batch.new
  end

  # GET /batches/1/edit
  def edit
  end

  # POST /batches
  # POST /batches.json
  def create
    @batch = Batch.new(batch_params)

    respond_to do |format|
      if @batch.save
        format.html { redirect_to @batch, notice: 'Batch was successfully created.' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batches/1
  # PATCH/PUT /batches/1.json
  def update
    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to @batch, notice: 'Batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render :edit }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    @batch.destroy
    respond_to do |format|
      format.html { redirect_to batches_url, notice: 'Batch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batch
      @batch = Batch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def batch_params
      params.require(:batch).permit(:year)
    end
end

app/controllers/depts_controller.rb
class DeptsController < ApplicationController
  before_action :set_dept, only: [:show, :edit, :update, :destroy]

  # GET /depts
  # GET /depts.json
  def index
    @depts = Dept.all
  end

  # GET /depts/1
  # GET /depts/1.json
  def show
  end

  # GET /depts/new
  def new
    @dept = Dept.new
  end

  # GET /depts/1/edit
  def edit
  end

  # POST /depts
  # POST /depts.json
  def create
    @dept = Dept.new(dept_params)

    respond_to do |format|
      if @dept.save
        format.html { redirect_to @dept, notice: 'Dept was successfully created.' }
        format.json { render :show, status: :created, location: @dept }
      else
        format.html { render :new }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /depts/1
  # PATCH/PUT /depts/1.json
  def update
    respond_to do |format|
      if @dept.update(dept_params)
        format.html { redirect_to @dept, notice: 'Dept was successfully updated.' }
        format.json { render :show, status: :ok, location: @dept }
      else
        format.html { render :edit }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depts/1
  # DELETE /depts/1.json
  def destroy
    @dept.destroy
    respond_to do |format|
      format.html { redirect_to depts_url, notice: 'Dept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dept
      @dept = Dept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dept_params
      params.require(:dept).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :role, :actor, :path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/batches/_form.html.erb
<%= form_for(@batch) do |f| %>
  <% if @batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
      <% @batch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing Batch</h1>

<%= render 'form' %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Batches</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.year %></td>
        <td><%= link_to 'Show', batch %></td>
        <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
        <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Batch', new_batch_path %>

app/views/batches/new.html.erb
<h1>New Batch</h1>

<%= render 'form' %>

<%= link_to 'Back', batches_path %>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @batch.year %>
</p>

<%= link_to 'Edit', edit_batch_path(@batch) %> |
<%= link_to 'Back', batches_path %>

app/views/depts/_form.html.erb
<%= form_for(@dept) do |f| %>
  <% if @dept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dept.errors.count, "error") %> prohibited this dept from being saved:</h2>

      <ul>
      <% @dept.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/depts/edit.html.erb
<h1>Editing Dept</h1>

<%= render 'form' %>

<%= link_to 'Show', @dept %> |
<%= link_to 'Back', depts_path %>

app/views/depts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Depts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @depts.each do |dept| %>
      <tr>
        <td><%= dept.name %></td>
        <td><%= link_to 'Show', dept %></td>
        <td><%= link_to 'Edit', edit_dept_path(dept) %></td>
        <td><%= link_to 'Destroy', dept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dept', new_dept_path %>

app/views/depts/new.html.erb
<h1>New Dept</h1>

<%= render 'form' %>

<%= link_to 'Back', depts_path %>

app/views/depts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dept.name %>
</p>

<%= link_to 'Edit', edit_dept_path(@dept) %> |
<%= link_to 'Back', depts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spcet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :actor %><br>
    <%= f.text_field :actor %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Role</th>
      <th>Actor</th>
      <th>Path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.role %></td>
        <td><%= user.actor %></td>
        <td><%= user.path %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Actor:</strong>
  <%= @user.actor %>
</p>

<p>
  <strong>Path:</strong>
  <%= @user.path %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>